# Dependencies
dependencies:
  - name: secret
    condition: exists
  - name: deployment
# General
namespace: python-apps
name: app
replicaCount: 2
# Service
service:
  type: LoadBalancer
  port: 5000
  targetPort: 5000
# Deployment
deployment:
  acr: acrdevsample2024.azurecr.io
  image: app
  tag: latest
  containerPort: 5000
  secretName: mongodb-connection-secret
# Ingress
ingress:
  host: devaks-avziq1v5.hcp.eastus.azmk8s.io
  service_port: 5000
# Secret
secret:
  secretName: mongodb-connection-secret
