apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.deployment.acr }}/{{ .Values.deployment.image }}:{{ .Values.deployment.tag }}
        ports:
          - containerPort: {{ .Values.deployment.containerPort }}
        env:
          - name: MONGODB_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: {{ .Values.deployment.secretName }}
                key: connection_string
